Algoritmo "semnome"
// CONCEITO DE ALGORITIMOS
// Gilberto 
// Descrição   : 1. Calcule a área de um terreno quadrado e mostre o resultado na tela.
// Autor(a)    : Luiz F.
// Data atual  : 30/08/2023
Var


lado, area : real


Inicio

escreva("digite o tamanho do lado do terreno: ")
leia(lado)

area <- lado * lado

escreva("a area total do terreno ao quadrado é: ", area)


Fimalgoritmo