Algoritmo "atividades"
// CONCEITO DE ALGORITIMOS
// Gilberto 

// Descrição   : Crie um algoritmo que receba um número digitado pelo usuário
// e mostre o valor de seu dobro.

// Autor: Luiz F.
// Data atual  : 29/08/2023
Var
nota:  real
n1, n2: real

Inicio
  escreva ("digite uma nota")
  leia (n1)
  escreva ("digite a segunda nota")
  leia (n2)
  
  nota <- n1 * n2
  
  escreva (nota)


Fimalgoritmo