Algoritmo "repetição"
  //ESCREVA UM NUMERO QUE RECEBA 1 NUMERO MAIOR OU IGUAL A 0 E IMPRIMA O
  // VALOR. SE O NUMERO FOR NEGATIVO, O PROXIMO DEVERA PEDIR PARA O USUARIO
  //DIGITE O NUMERO NOVAMENTE
Var
n1: inteiro
Inicio

   escreva ("digite um valor")
   leia(n1)
   enquanto (n1 < 0) faca
      escreva ("digite um numero positivo")
      leia(n1)
   fimenquanto
  escreva("o numero digitado foi ", n1)

fimalgoritmo