Algoritmo "repetição"
//Escreva um algoritmo que leia diversos
//números positivos e escreva, para cada um,
//seu dobro. Quando o usuário digitar um
//número negativo o programa deve encerrar.
Var
numero: inteiro
Inicio
   escreva("digite um numero")
   leia (numero)
   enquanto  (numero > 0) faca
      numero <- numero * 2
      escreval(numero)
      escreva("digite um numero")
      leia (numero)
   fimenquanto
      

fimalgoritmo