Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Gilberto 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/10/2023
Var
mediaFinalAluno : inteiro

Inicio
mediaFinalAluno <- 70

se (mediaFinalAluno>= 70) entao
         escreva("Aluno foi aprovado")
senao
         escreva ("Aluno foi reprovado")
fimse

Fimalgoritmo