Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/08/2023
Var
algoritmo   "Exemplo"
	a, b : inteiro
inicio
	para a de 1 ate 10 faca
		escreval( "Digite um valor:")
		leia(b)
	fimpara
fimalgoritmo