Algoritmo "yt exercicio 1"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Gilberto 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/10/2023
Var
 salario, salarioMinimo, quantidade : real

Inicio
escreva ("salario")
leia(salario)
escreva ("salario minimo")
leia (salarioMinimo)
quantidade<-salario/salarioMinimo
escreva ("quatidade de salario:", quantidade)

Fimalgoritmo